### ISSUE TITLE
How is Gravity Direction Determined

### ISSUE THREAD

**Issue by MartaYang** [zju3dv/GVHMR#1]
Hi,

Thanks for your amazing work! I’m wondering how the gravity direction is determined in the first place. Is it assumed that a specific axis (e.g., Y-axis pointing down) represents gravity, or is it estimated from DPVO?

Any insights would be much appreciated!

**Comment by zehongs** [comment]
Hi, thanks for your interest!

The gravity direction in the world coordinates is only required during training. Please refer to https://github.com/zju3dv/GVHMR/blob/84f4339ff589da5b553a3e4d8b38c7b5c0459321/hmr4d/utils/geo/hmr_global.py#L7
During inference, GVHMR predicts human pose **relative to** the GV coordinates. In other words, we do not explicitly predict the gravity direction.

**Comment by MartaYang** [comment]
Thanks for your clarification!
