### ISSUE TITLE
Is there a way to detect multiple people?

### ISSUE THREAD

**Issue by carlosedubarreto** [zju3dv/GVHMR#11]
While testing the code, I noticed it executes only for one person, is there a way to do it for multiple people?

you can see the result of my test here.
https://github.com/user-attachments/assets/9b00d290-5e31-4c84-9e7b-50509418164b

thanks a lot for the code, the result is sooo good.!!

**Comment by kexul** [comment]
https://github.com/zju3dv/GVHMR/blob/91cf78086e017f55d9978100ab73db90bb7788a5/tools/demo/demo.py#L98

Maybe change the top1 to other value would do the trick. I believe it's quite easy to modify the code and pass a new parameter.

**Comment by carlosedubarreto** [comment]
Thanks a ot I'll give it a try

**Comment by carlosedubarreto** [comment]
Thanks a lot @kexul , I added a variable to select the person that I want to process and it worked 🎉
![image](https://github.com/user-attachments/assets/199a55e0-598e-427b-abaf-706c463a966d)

**Comment by xiaoc1212** [comment]
> ![image](https://private-user-images.githubusercontent.com/4061130/368102133-199a55e0-598e-427b-abaf-706c463a966d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNDg2NTIsIm5iZiI6MTcyNzI0ODM1MiwicGF0aCI6Ii80MDYxMTMwLzM2ODEwMjEzMy0xOTlhNTVlMC01OThlLTQyN2ItYWJhZi03MDZjNDYzYTk2NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjVUMDcxMjMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQ4MGY5ZWI3NTFhNzUzZTUzNGJkNzc4OWZiOThkYjc0Mzk0ODgxNmExM2ZmODM5MDQzNzVjODdkN2Y1NGI2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.hUbYOCOg0jcHxG06OKmI4heFfUm0hLKqcEe6wUp1OLc)

Hi,Carlos， can you share the specific implementation method with me?

**Comment by kexul** [comment]
@xiaoc1212 check this https://github.com/zju3dv/GVHMR/issues/10#issuecomment-2360421799

**Comment by xiaoc1212** [comment]
> @xiaoc1212 检查此 [#10 (comment)](https://github.com/zju3dv/GVHMR/issues/10#issuecomment-2360421799)

thanks a lot
