### ISSUE TITLE
How to convert .pt format to .pkl for smpl

### ISSUE THREAD

**Issue by bboyalong01** [zju3dv/GVHMR#12]
Hello, how to convert the output .pt format to smpl .pkl

**Comment by zehongs** [comment]
Use `result = torch.load("hmr4d_results.pt")` to load pt file.
To convert pytorch tensor to numpy ndarray, you can refer to this: https://github.com/zju3dv/GVHMR/issues/10#issue-2527919649

**Comment by bboyalong01** [comment]
> Use `result = torch.load("hmr4d_results.pt")` to load pt file. To convert pytorch tensor to numpy ndarray, you can refer to this: [#10 (comment)](https://github.com/zju3dv/GVHMR/issues/10#issue-2527919649)
Okay, thank you very much
