### ISSUE TITLE
Are there any plans to support more difficult moves?

### ISSUE THREAD

**Issue by bboyalong01** [zju3dv/GVHMR#16]
Hello, for some hip-hop movements, such as breaking, there are a lot of handstands, spinning difficult movements, the support is not so good, this kind of movement training is not easy to collect, right? I look at this kind of action, and the motion capture of the video can't support it very well at the moment

**Comment by zehongs** [comment]
Hi, I believe it’s probably due to the training data. Unfortunately, we don’t have the bandwidth to scale the data at this time. But I'll add this to my potential todo list.

**Comment by bboyalong01** [comment]
> Hi, I believe it’s probably due to the training data. Unfortunately, we don’t have the bandwidth to scale the data at this time. But I'll add this to my potential todo list.



> Hi, I believe it’s probably due to the training data. Unfortunately, we don’t have the bandwidth to scale the data at this time. But I'll add this to my potential todo list.

That's really nice
