### ISSUE TITLE
SMPL to SIM

### ISSUE THREAD

**Issue by naivate** [zju3dv/GVHMR#17]
Hello,

Thank you for your great work! I would like to know how to align a given SMPL sequence from mocap perfectly with the ground in the simulation.

**Comment by zehongs** [comment]
Hi, thanks for your interest!
First, identify the gravity axis in your simulation (for example, in PHC+Isaac Gym, it’s the z-axis). 
Then, rotate our y-axis aligned results like this to match the simulation's axis:
```python
verts = verts[..., [0, 2, 1]]
verts[..., 1] *= -1
```
Next, subtract the foot joint height. We found that fitting a pseudo-ground plane to the z-values can further improve stability:
```python
min_z = verts[:, :, 2].min(1).values.numpy()  # (L)
degree = 1
coefficients = np.polyfit(np.arange(len(min_z)), min_z, degree)
polynomial = np.poly1d(coefficients)
fitted_values = polynomial(np.arange(len(min_z)))
verts[:, :, 2] -= torch.from_numpy(fitted_values)[:, None].to(verts)
```

**Comment by kexul** [comment]
> Hi, thanks for your interest! First, identify the gravity axis in your simulation (for example, in PHC+Isaac Gym, it’s the z-axis). Then, rotate our y-axis aligned results like this to match the simulation's axis:
> 
> ```python
> verts = verts[..., [0, 2, 1]]
> verts[..., 1] *= -1
> ```
> 
> Next, subtract the foot joint height. We found that fitting a pseudo-ground plane to the z-values can further improve stability:
> 
> ```python
> min_z = verts[:, :, 2].min(1).values.numpy()  # (L)
> degree = 1
> coefficients = np.polyfit(np.arange(len(min_z)), min_z, degree)
> polynomial = np.poly1d(coefficients)
> fitted_values = polynomial(np.arange(len(min_z)))
> verts[:, :, 2] -= torch.from_numpy(fitted_values)[:, None].to(verts)
> ```

Hi @zehongs , Would you mind add an example of using GVHMR result in PHC? Many thanks!

**Comment by zehongs** [comment]
Hi @kexul! 
Unfortunately, it is still part of an ongoing project, so we do not plan to release it soon.
