### ISSUE TITLE
重力方向问题

### ISSUE THREAD

**Issue by aime1126** [zju3dv/GVHMR#20]
您好！我很幸运看到了如此优秀的工作！
有几个疑问希望能得到您的解答！
1. 重力的方向是根据每个数据集的世界坐标系人为进行规定吗？
2. 网络是直接预测出每帧相对于重力坐标系的旋转嘛？然后 gt 用的是将数据集世界坐标系下的 gt smpl参数的全局旋转用get_R_c2gv函数手动推算出来的嘛？
3. 在推理时，网络预测重力坐标系下的全局轨迹，这个重力坐标系是怎么得到的，也是人为规定的吗，还是网络会预测出合适的重力方向？
希望能得到您的回复！

**Comment by aime1126** [comment]
如果是假设的重力坐标系，会不会导致严重的累计误差？

**Comment by zehongs** [comment]
感谢您的关注！
1. 训练时需要知道每个数据集的重力方向。比如AMASS、BEDLAM和H36M的重力方向都是沿坐标轴的。
2. 是。是。
3. 网络预测（1）每一帧人相对于GV系的旋转，（2）然后按照论文中所说的方式拼接不同帧。
4. 仅针对“全局旋转”，我们的方法有相当鲁棒的性能。不存在系统性的累积误差。
