### ISSUE TITLE
ImportError: cannot import name 'Extractor' from 'hmr4d.utils.preproc'

### ISSUE THREAD

**Issue by ZANGYA** [zju3dv/GVHMR#22]
This was my third attempt to reinstall it, and each time I entered the video it would say "cannot import name 'Extractor'". May I ask what causes this? I checked the root directory for no missing files.
![error](https://github.com/user-attachments/assets/8ffab59c-cfda-4243-9185-7b21597021ce)

**Comment by dorukcandan** [comment]
I'm having the same problem

**Comment by crsiper** [comment]
Try revising the import lines as following:
```
# from hmr4d.utils.preproc import Tracker, Extractor, VitPoseExtractor, SLAMModel
from hmr4d.utils.preproc.tracker import Tracker
from hmr4d.utils.preproc.vitfeat_extractor import Extractor
from hmr4d.utils.preproc.vitpose import VitPoseExtractor
from hmr4d.utils.preproc.slam import SLAMModel
```
