### ISSUE TITLE
Circular Import with visual odometry

### ISSUE THREAD

**Issue by cetsell** [zju3dv/GVHMR#26]
I get a few errors trying to run without the "-s" parameter on moving camera video.
First, I get:
`Failed to import DPVO modules: No module named 'dpvo'`
which doesn't seem to stop the actual job, but then this:
```
/GVHMR/hmr4d/utils/preproc/slam.py", line 51, in track
    cfg.merge_from_file(self.dpvo_cfg)
NameError: name 'cfg' is not defined
```
I tried adding some missing __init__.py files but it still can't seem to import this module. Is there a smoother process to get visual odometry working?

**Comment by IsshikiHugh** [comment]
Hi! It seems like your DPVO fails to be installed successfully. This issue probably helps! https://github.com/zju3dv/GVHMR/issues/5
