### ISSUE TITLE
Final output 

### ISSUE THREAD

**Issue by Abocg** [zju3dv/GVHMR#3]
Absolutely amazing work . But may I ask what the final output. Is it only the human geometry or can we get .bvh or .fbx motion. Am new in this field. Sorry if am asking a stupid question

**Comment by zehongs** [comment]
Thanks for your interest!
The output `pt` file contains `smpl_params_global`, `smpl_params_incam`, `K_fullimg`.
To obtain a BVH or FBX file, I suggest looking into a conversion script that processes SMPL(-X) parameters (`smpl_params_global`).

**Comment by kexul** [comment]
> Thanks for your interest! The output `pt` file contains `smpl_params_global`, `smpl_params_incam`, `K_fullimg`. To obtain a BVH or FBX file, I suggest looking into a conversion script that processes SMPL(-X) parameters (`smpl_params_global`).

Is this the standard smplx parameters, I just load the '.pt' file and the result['smpl_params_global']['body_pose'].shape is [191,63], which means there are 21 joints.  For smplx, there should be 145 joints, for vanilla smpl, there should be 24 joints. 

Would you mind provide the joint map? Thanks! @zehongs
