### ISSUE TITLE
Floating issue

### ISSUE THREAD

**Issue by Shi-Qi-Li** [zju3dv/GVHMR#33]
Hi author,
Thanks for your great work.
I am trying to recover the player from basketball videos. However, I found there is a floating issue. Do you have any suggestions for tackling this problem? Any help is appreciated.

Here is an example, I simply modify the camera height in render for better illustration.

https://github.com/user-attachments/assets/6f3b6437-0a7f-4b88-bf84-b5bb6bb7dc27

![root](https://github.com/user-attachments/assets/8bdbef57-dc20-4730-bed0-1937a702a8d0)

**Comment by zehongs** [comment]
Hi, this is a known issue, as the translation is not constrainted. We plan to improve it in our future work.
In your case, where the ground is of the same height, a possible solution is to fit a ground plane using the following code. Some modifications may be necessary...
https://github.com/zju3dv/GVHMR/issues/17#issuecomment-2361069686

**Comment by Shi-Qi-Li** [comment]
> Hi, this is a known issue, as the translation is not constrainted. We plan to improve it in our future work. In your case, where the ground is of the same height, a possible solution is to fit a ground plane using the following code. Some modifications may be necessary... [#17 (comment)](https://github.com/zju3dv/GVHMR/issues/17#issuecomment-2361069686)

Thank you for your prompt reply and suggestion. I look forward to your further work.

**Comment by Neutree** [comment]
> Hi, this is a known issue, as the translation is not constrainted. We plan to improve it in our future work. In your case, where the ground is of the same height, a possible solution is to fit a ground plane using the following code. Some modifications may be necessary... [#17 (comment)](https://github.com/zju3dv/GVHMR/issues/17#issuecomment-2361069686)

hello~, any progress after one years later?
