### ISSUE TITLE
Wrong foot pose

### ISSUE THREAD

**Issue by kexul** [zju3dv/GVHMR#35]
Hi, as shown in the following video, the foot pose is not aligned with the video at some point.
![image](https://github.com/user-attachments/assets/a25cd239-cb30-4e29-8d8c-b812b2571065)

Is there anything we can do to enhance it?
I noticed that the foot joint is not detected in the keypoint detection model, so it's inferred solely by the image feature? If that's true, adding this kind of training data would not help much?
Another solution might be using another keypoint detection model which can detect feet and correct the pose in the post processing stage, is that feasible? 

Many thanks!

https://github.com/user-attachments/assets/3a92ed52-e485-4619-aee3-bb7fc9c3ccaa

**Comment by zehongs** [comment]
@kexul 
I agree with your analysis.
Currently, the most common and promising thing is adding a postprocssing. For example, this [project](https://github.com/mks0601/ExAvatar_RELEASE/tree/main/fitting) might help.
