### ISSUE TITLE
how do you prevent mesh collision?

### ISSUE THREAD

**Issue by yankainan** [zju3dv/GVHMR#36]
thank for your excellent work!
how do you prevent mesh inter penetration?

**Comment by zehongs** [comment]
Hi, GVHMR does not handle mesh collision.

**Comment by yankainan** [comment]
> Hi, GVHMR does not handle mesh collision.

thanks for your reply! by the way, do u know how to prevent interpenetration during reconstruction?

**Comment by zehongs** [comment]
You can  try to optimize smplx parameters to minimize both gvhmr-initialization-loss and collision-loss.

**Comment by yankainan** [comment]
> You can try to optimize smplx parameters to minimize both gvhmr-initialization-loss and collision-loss.

ok! but i dont know how to define collision-loss : (
