### ISSUE TITLE
Can Hand and Finger Movements be Reproduced?

### ISSUE THREAD

**Issue by W-Nabe** [zju3dv/GVHMR#4]
Thank you for your amazing work! It's been fun trying it out on various videos.

I have one question.
GVHMR seems to be a model focused on reproducing body movements, but is it possible to reproduce hand and finger movements as well?

[https://github.com/HongwenZhang/PyMAF-X](https://www.google.com/url?sa=E&q=https%3A%2F%2Fgithub.com%2FHongwenZhang%2FPyMAF-X)
I was wondering if it would be possible to achieve full-body reproduction like the project above with the accuracy of GVHMR, so I just wanted to confirm.

**Comment by zehongs** [comment]
Yes, GVHMR only predicts body movement.
To add finger movement, we need to predict the hand parameters of SMPLX, which is set to zero in GVHMR. 
A quick approach is to combine our results with other methods, like PyMAF-X.

**Comment by W-Nabe** [comment]
Thank you for your prompt response!
