### ISSUE TITLE
How do you get the image feature?

### ISSUE THREAD

**Issue by fengq1a0** [zju3dv/GVHMR#41]
The ViT image encoder produces a feature of shape **[B, 1280, 16, 12]**. It then passes through 6 cross-attention layers to decode the feature into a vector of shape [B, 1024].

Do you use the final decoded feature [B, 1024] as input, or do you use an intermediate output from one of the 6 cross-attention layers?

**Comment by zehongs** [comment]
Hi, thanks for your interest in GVHMR.
We use the final decoded feature with a dimension of 1024 as input. This follows WHAM.

**Comment by fengq1a0** [comment]
Very nice work! And thank you for your answer.
