### ISSUE TITLE
 from hmr4d.utils.preproc import Tracker, Extractor, VitPoseExtractor, SLAMModel

### ISSUE THREAD

**Issue by ZhangYingHao7** [zju3dv/GVHMR#43]
Traceback (most recent call last):
  File "F:\GVHMR\tools\demo\demo.py", line 23, in <module>
    from hmr4d.utils.preproc import Tracker, Extractor, VitPoseExtractor, SLAMModel
ImportError: cannot import name 'Extractor' from 'hmr4d.utils.preproc' (F:\GVHMR\hmr4d\utils\preproc\__init__.py)

**Comment by F-DR** [comment]
How did you solve it? Same error message
