### ISSUE TITLE
NameError: name 'cfg' is not defined

### ISSUE THREAD

**Issue by kexul** [zju3dv/GVHMR#5]
Hi, thanks for the great work! I encountered a problem when using the demo.py,would mind help?

Command I used: 
```
!python /content/GVHMR/tools/demo/demo.py --video=/content/test.mp4
```
Output:
```
DPVO:   0% 0/155 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/content/GVHMR/tools/demo/demo.py", line 289, in <module>
    run_preprocess(cfg)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/content/GVHMR/tools/demo/demo.py", line 143, in run_preprocess
    ret = slam.track()
  File "/content/GVHMR/hmr4d/utils/preproc/slam.py", line 51, in track
    cfg.merge_from_file(self.dpvo_cfg)
NameError: name 'cfg' is not defined
```

**Comment by zehongs** [comment]
Hi, are you running this command from the `/content/GVHMR` directory?

**Comment by kexul** [comment]
> Hi, are you running this command from the `/content/GVHMR` directory?

Yes, I'm using the ipython notebook provided by camenduru https://github.com/camenduru/GVHMR-jupyter

**Comment by zehongs** [comment]
This is a great Colab example from camenduru. However, I'm not familiar with the details, and this issue seems to be on the DPVO side. The intallation of DPVO may be problematic.. 

Since the environment should be similar, I suggest following our docs/INSTALL.md and running the demo command `python tools/demo/demo.py --video=docs/example_video/tennis.mp4 -s`.

**Comment by IsshikiHugh** [comment]
> > Hi, are you running this command from the `/content/GVHMR` directory?
> 
> Yes, I'm using the ipython notebook provided by camenduru https://github.com/camenduru/GVHMR-jupyter

Hi, just in case you haven't solved the problem, you can also try our new colab demo here:

https://colab.research.google.com/drive/1N9WSchizHv2bfQqkE9Wuiegw_OT7mtGj?usp=sharing

**Comment by Lidhra** [comment]
I had the same problem when running locally.
Just add "-s" at the end and the video was processed successfully

`!python /content/GVHMR/tools/demo/demo.py --video=/content/test.mp4 -s`

**Comment by kexul** [comment]
> This is a great Colab example from camenduru. However, I'm not familiar with the details, and this issue seems to be on the DPVO side. The intallation of DPVO may be problematic..
> 
> Since the environment should be similar, I suggest following our docs/INSTALL.md and running the demo command `python tools/demo/demo.py --video=docs/example_video/tennis.mp4 -s`.

Thanks! But the camera in my input video is not static, can I use `-s` in this case?

**Comment by kexul** [comment]
> > > Hi, are you running this command from the `/content/GVHMR` directory?
> > 
> > 
> > Yes, I'm using the ipython notebook provided by camenduru https://github.com/camenduru/GVHMR-jupyter
> 
> Hi, just in case you haven't solved the problem, you can also try our new colab demo here:
> 
> https://colab.research.google.com/drive/1N9WSchizHv2bfQqkE9Wuiegw_OT7mtGj?usp=sharing

Thank you so much, I'll try it!

**Comment by yisuanwang** [comment]
在不使用-s 时出现NameError: name 'cfg' is not defined 可以通过下面方法解决：
1.在 demo.py修改将 cfg 传入 ret = slam.track(cfg=cfg)
2.在```GVHMR/hmr4d/utils/preproc/slam.py```里修改
```
        if self.slam is None:
            cfg.BUFFER_SIZE = self.buffer
            self.slam = DPVO(cfg, self.dpvo_ckpt, ht=image.shape[1], wd=image.shape[2], viz=False)
```
3.在```third_party/GVHMR/hmr4d/configs/demo.yaml```后面添加
```
# ================================ #
#          dpvo settings           #
# ================================ #
### DPVO Config File ###

# VO config (increase for better accuracy)
PATCHES_PER_FRAME: 96
REMOVAL_WINDOW: 22
OPTIMIZATION_WINDOW: 10
PATCH_LIFETIME: 13

# threshold for keyframe removal
KEYFRAME_THRESH: 15.0

# camera motion model
MOTION_MODEL: 'DAMPED_LINEAR'
MOTION_DAMPING: 0.5

# maybe use mixed precision for inference
MIXED_PRECISION: True

CENTROID_SEL_STRAT: 'RANDOM'

# max number of keyframes
BUFFER_SIZE: 4096

# threshold for keyframe removal
KEYFRAME_INDEX: 4

# Loop closure
LOOP_CLOSURE: False
BACKEND_THRESH: 64.0
MAX_EDGE_AGE: 1000
GLOBAL_OPT_FREQ: 15

# Classic loop closure
CLASSIC_LOOP_CLOSURE: False
LOOP_CLOSE_WINDOW_SIZE: 3
LOOP_RETR_THRESH: 0.04
```

其次通过 GVHMR 给出的 install.md可能导致 DPVO 没有正确安装，并且在 slam.py中忽略了这个报错：
```
try:
    from dpvo.utils import Timer
    from dpvo.dpvo import DPVO
    from dpvo.config import cfg
except:
    pass
```
这可能导致 DPVO 没有正确启动```GVHMR/third-party/DPVO/cuda_corr.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZNK3c105Error4whatEv```，我使用下面的方法解决了这个问题：
```
cd GVHMR/third-party/DPVO
rm -rf build
rm -rf dist
rm -rf *.egg-info
rm -rf cuda_corr.cpython-310-x86_64-linux-gnu.so

# 重新编译
python setup.py build_ext --inplace
```
