### ISSUE TITLE
Export results to blender ?

### ISSUE THREAD

**Issue by Lidhra** [zju3dv/GVHMR#8]
Greetings!!!

I am attracted to SMPL models, I managed to get your demo working and process my own video with your project.

I would appreciate help or advice to export the results to Blender or Unity, I don't know much to be honest and I'm trying to learn, I would appreciate any help or advice you can give me :)

(Excuse my English from the translator)

**Comment by zehongs** [comment]
Hi thanks for your interest! Unfortunatly, exporting result to blender or unity is not the focus of this project.
I believe you can try something like SMPL to Blender script. For example, https://github.com/Meshcapade/SMPL_blender_addon .

**Comment by Lidhra** [comment]
Thanks for info.

**Comment by Amble12345** [comment]
#84
